# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  start-express:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/Users/mrm/Documents/TECH/React/Redux/Co-exist/react-express-app/server
    steps:
      - run:
          name: write directory
          command: pwd
      - checkout
      - run:
          name: Workaround old Docker images with incorrect $HOME
          command: |
            if [[ "$HOME" == "/" ]]; then
              export HOME=$(getent passwd $(id -u) | awk -F ':' '{print $6}')
            fi
      - run:
          name: Install dependencies
          command: npm install --no-package-lock
      - run:
          name: Start Express server
          command: npm start
  start-client:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/Users/mrm/Documents/TECH/React/Redux/Co-exist/react-express-app/client
    steps:
      - run:
          name: write directory
          command: pwd
      - checkout
      - run:
          name: Workaround old Docker images with incorrect $HOME
          command: |
            if [[ "$HOME" == "/" ]]; then
              export HOME=$(getent passwd $(id -u) | awk -F ':' '{print $6}')
            fi
      - run:
          name: Install dependencies
          command: npm install --no-package-lock
      - run:
          name: Start React app
          command: npm start
  start-json-server:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/Users/mrm/Documents/TECH/React/Redux/Co-exist/react-express-app/server
    steps:
      - run:
          name: write directory
          command: pwd
      - checkout
      - run:
          name: Workaround old Docker images with incorrect $HOME
          command: |
            if [[ "$HOME" == "/" ]]; then
              export HOME=$(getent passwd $(id -u) | awk -F ':' '{print $6}')
            fi
      - run:
          name: Install dependencies
          command: npm install --no-package-lock
      - run:
          name: Start JSON server
          command: json-server --watch data.json
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | bash
      - run:
          name: Login to Railway
          command: railway login
      - run:
          name: Link project to Railway
          command: railway link
      - run:
          name: Deploy to Railway
          command: railway deploy --env NODE_ENV=production --wait
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - start-express:
          filters:
            branches:
              only: project-add-form
      - start-client:
          filters:
            branches:
              only: project-add-form
      - start-json-server:
          filters:
            branches:
              only: project-add-form
      - deploy:
          requires:
            - start-express
            - start-client
            - start-json-server
          filters:
            branches:
              only: project-add-form