version: 2.1

jobs:
  start-express:
    docker:
      - image: cimg/node:14.17.0
    working_directory: /my-dev-branch
    steps:
      - checkout:
          path: /my-dev-branch
          repository: Pacomrm/Co-Exist
      - run:
          name: write directory
          command: pwd
      - run:
          name: Install getent
          command: sudo apt-get update && sudo apt-get install -y libc-bin
      - run:
          name: Check for getent command
          command: which getent
      - run:
          name: Print HOME environment variable
          command: echo "HOME=$HOME"
      - run:
          name: Workaround old Docker images with incorrect $HOME
          command: |
            if [[ "$HOME" == "/" ]]; then
              export HOME=$(getent passwd $(id -u) | awk -F ':' '{print $6}')
            fi
      - run:
          name: Install dependencies
          command: cd /my-dev-branch/server && npm install
      - run:
          name: Start Express server
          command: cd /my-dev-branch/server && npm start
  start-client:
    docker:
      - image: cimg/node:14.17.0
    working_directory: /my-dev-branch
    steps:
      - checkout:
          path: /my-dev-branch
          repository: Pacomrm/Co-Exist
      - run:
          name: write directory
          command: pwd
      - run:
          name: Workaround old Docker images with incorrect $HOME
          command: |
            if [[ "$HOME" == "/" ]]; then
              export HOME=$(getent passwd $(id -u) | awk -F ':' '{print $6}')
            fi
      - run:
          name: Install dependencies
          command: cd /my-dev-branch/client && npm install
      - run:
          name: Start React app
          command: cd /my-dev-branch/client && npm start
  start-json-server:
    docker:
      - image: cimg/node:14.17.0
    working_directory: /my-dev-branch
    steps:
      - checkout:
          path: /my-dev-branch
          repository: Pacomrm/Co-Exist
      - run:
          name: write directory
          command: pwd
      - run:
          name: Workaround old Docker images with incorrect $HOME
          command: |
            if [[ "$HOME" == "/" ]]; then
              export HOME=$(getent passwd $(id -u) | awk -F ':' '{print $6}')
            fi
      - run:
          name: Install dependencies
          command: cd /my-dev-branch/server && npm install
      - run:
          name: Start JSON server
          command: cd /my-dev-branch/server json-server --watch data.json
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | bash
      - run:
          name: Login to Railway
          command: railway login
      - run:
          name: Link project to Railway
          command: railway link
      - run:
          name: Deploy to Railway
          command: railway deploy --env NODE_ENV=production --wait
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - start-express:
          filters:
            branches:
              only: project-add-form
      - start-client:
          filters:
            branches:
              only: project-add-form
      - start-json-server:
          filters:
            branches:
              only: project-add-form
      - deploy:
          requires:
            - start-express
            - start-client
            - start-json-server
          filters:
            branches:
              only: project-add-form