version: 2.1
jobs:
  my-job:
    docker:
      - image: my-docker-image
    environment:
      HOME: /root
    steps:
      - checkout
      - run:
          name: Set HOME environment variable
          command: echo "HOME=${HOME}"